development:
  adapter: postgresql
  encoding: unicode
  database: cemetery_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cemetery_test
  pool: 5
  username: postgres
  password:
